"""Fixed scenario pool for the human-play (gamification) tab.

Each scenario is a self-contained layout (cranes / lifts / restricted zones)
plus env config. Scenarios are DATA-DRIVEN now: 21 maps over difficulty 1-5
(counts 3/5/5/5/3), generated by ``_gen_scenarios.py`` into
``crane_core/scenarios_data.py``. Edit coordinates there to tune.

- ``difficulty`` (1-5 → ★ stars) is the primary axis. As it rises: more cranes/
  lifts, more restricted zones, wider weight/height spread, and (from ★3) some
  lifts placed INSIDE restricted zones (crane stands outside, boom reaches in).
- ``tier`` is a coarse 3-band grouping for the list filter only:
  tutorial=★1-2 (입문), standard=★3 (표준), expert=★4-5 (고급).

A scenario layout/config is dicts only (no env instance) so it can be
serialized to JSON and re-used by both /api/game/scenarios (frontend list)
and /api/game/session/* (session creation).
"""
from __future__ import annotations

import copy
from typing import Dict, List, Optional


# Reasonable rated-load curve for the expert tier. (radius_m, capacity_t)
# Points should be sorted by radius; capacity decreases as radius grows.
EXPERT_CAPACITY_CURVE = [
    [8.0, 28.0],
    [12.0, 22.0],
    [16.0, 16.0],
    [20.0, 11.0],
    [24.0, 7.0],
]


# 2D rated-load chart (boom-length × radius), the mobile-crane standard format and
# the DEFAULT rated-load model for every scenario. One capacity-vs-radius curve per
# boom length: extending the boom to reach higher (or farther) derates capacity at
# the same horizontal radius. Reaching radius R at height H needs a boom of slant
# length sqrt(R²+H²); the env picks the SHORTEST boom that covers it (most capacity)
# and reads capacity at R from that boom's curve. The longest boom (42m) sets the
# absolute reach limit. The shortest boom is 13m (a real 50t main-boom minimum) so
# placement heights in the 8–18m range actually push a close-in lift onto a longer
# boom and derate it. Radius range reaches 27m to cover the largest crane_radius.
DEFAULT_CAPACITY_CHART = [
    {"boom_len": 13.0, "curve": [[3, 50], [6, 42], [9, 33], [12, 26]]},
    {"boom_len": 22.0, "curve": [[3, 46], [6, 38], [9, 30], [12, 24], [15, 18], [18, 13], [21, 10]]},
    {"boom_len": 32.0, "curve": [[3, 40], [6, 32], [9, 24], [12, 19], [15, 14], [18, 10], [24, 6]]},
    {"boom_len": 42.0, "curve": [[3, 34], [6, 26], [9, 19], [12, 15], [15, 10], [18, 7],  [27, 4]]},
]

# Back-compat alias — earlier code referenced EXPERT_CAPACITY_CHART.
EXPERT_CAPACITY_CHART = DEFAULT_CAPACITY_CHART


def _default_config(
    fixed_duration: float = 25.0,
    setup_time: float = 10.0,
    teardown_time: float = 5.0,
    crane_radius: float = 18.0,
    site_size: float = 100.0,
    candidate_k: int = 999,  # human play: unrestricted candidate list
    max_steps: int = 220,
    crane_capacity_curve: Optional[List[List[float]]] = None,
    lift_weight_min_t: float = 0.0,
    lift_weight_max_t: float = 50.0,
    # 2.5D height parameters
    crane_boom_len: float = 0.0,   # default boom length (m); 0 = 2D mode
    lift_z_min: float = 0.0,       # random lift departure/arrival height range (m)
    lift_z_max: float = 0.0,
    crane_capacity_chart: Optional[List[Dict]] = DEFAULT_CAPACITY_CHART,  # 2D rated-load chart (default model); supersedes the 1D curve
) -> Dict:
    cfg = {
        "fixed_duration": fixed_duration,
        "setup_time": setup_time,
        "teardown_time": teardown_time,
        "crane_radius": crane_radius,
        "candidate_k": candidate_k,
        "max_steps": max_steps,
        "site_width": site_size,
        "site_height": site_size,
        "lift_weight_min_t": lift_weight_min_t,
        "lift_weight_max_t": lift_weight_max_t,
        "default_lift_weight_t": 10.0,
        "crane_boom_len": crane_boom_len,
        "lift_z_min": lift_z_min,
        "lift_z_max": lift_z_max,
    }
    if crane_capacity_curve:
        cfg["crane_capacity_curve"] = crane_capacity_curve
    if crane_capacity_chart:
        cfg["crane_capacity_chart"] = crane_capacity_chart
    return cfg


# ─────────────────────────────────────────────────────────────────────────────
# Build SCENARIOS from the generated data module. Each spec carries the layout
# (cranes/lifts/zones with weight_t + z baked in) and a crane_radius; config is
# assembled here so the 2D rated-load chart + 2.5D defaults apply uniformly.
# ─────────────────────────────────────────────────────────────────────────────
from crane_core.scenarios_data import SCEN_SPECS

# The easiest ★1 scenario doubles as the tutorial walkthrough entry point.
_WALKTHROUGH_ID = next((s["id"] for s in SCEN_SPECS if int(s.get("difficulty", 9)) == 1), None)

def _register_spec(spec: Dict) -> None:
    """Turn a SCEN_SPECS-shaped dict into a runnable SCENARIOS entry."""
    SCENARIOS[spec["id"]] = {
        "id": spec["id"],
        "tier": spec["tier"],
        "name": spec["name"],
        "description": spec["description"],
        "difficulty": int(spec["difficulty"]),
        "walkthrough": spec["id"] == _WALKTHROUGH_ID,
        # When True, PlaySession imposes a seeded-random erection order on this
        # scenario (dedicated "순서" maps). Absent/False on ordinary maps.
        "order_mode": bool(spec.get("order_mode", False)),
        "layout": spec["layout"],
        "config": _default_config(crane_radius=float(spec.get("cr", 20.0))),
    }
    # Fleet-sizing maps: {"min": int, "max": int} — the player picks the crane
    # count (and parks each crane) before the session starts. Absent elsewhere.
    if spec.get("crane_choice"):
        SCENARIOS[spec["id"]]["crane_choice"] = dict(spec["crane_choice"])


SCENARIOS: Dict[str, Dict] = {}
for _spec in SCEN_SPECS:
    _register_spec(_spec)

# Steel-frame erection map (self-contained feature package). Additive: the
# public scenario API is unchanged, this just appends one expert scenario.
try:
    from crane_core.steelframe import SPEC as _STEELFRAME_SPEC
    _register_spec(_STEELFRAME_SPEC)
except Exception as _e:  # pragma: no cover — never let it break the core pool
    import sys as _sys
    print(f"[scenarios] steel-frame map not loaded: {_e}", file=_sys.stderr)

# Pipe-rack corridor map (self-contained feature package, same additive pattern
# as the steel-frame map above). Appends one expert "선형 회랑" scenario.
try:
    from crane_core.corridor import SPEC as _CORRIDOR_SPEC
    _register_spec(_CORRIDOR_SPEC)
except Exception as _e:  # pragma: no cover — never let it break the core pool
    import sys as _sys
    print(f"[scenarios] corridor map not loaded: {_e}", file=_sys.stderr)

# Fleet-sizing map (self-contained feature package): the player chooses the
# crane count (1–3) + placement before starting; plays are priced with cost.py.
try:
    from crane_core.fleet import SPEC as _FLEET_SPEC
    _register_spec(_FLEET_SPEC)
except Exception as _e:  # pragma: no cover — never let it break the core pool
    import sys as _sys
    print(f"[scenarios] fleet map not loaded: {_e}", file=_sys.stderr)


# Tier groups for the frontend list view (coarse 3-band over the 5-star scale)
TIER_ORDER = ["tutorial", "standard", "expert"]
TIER_LABEL = {
    "tutorial": "입문",
    "standard": "표준",
    "expert": "고급",
}


def list_scenarios(tier: Optional[str] = None) -> List[Dict]:
    """Return scenario metadata (id, tier, name, description, difficulty,
    counts). Excludes full layout to keep the list payload small.

    Pass tier=None to get all scenarios sorted by tier then difficulty then id.
    """
    out = []
    for s in SCENARIOS.values():
        if tier and s["tier"] != tier:
            continue
        out.append({
            "id": s["id"],
            "tier": s["tier"],
            "tier_label": TIER_LABEL.get(s["tier"], s["tier"]),
            "name": s["name"],
            "description": s["description"],
            "difficulty": s["difficulty"],
            "num_cranes": len(s["layout"]["cranes"]),
            "num_lifts": len(s["layout"]["lifts"]),
            "num_restricted": len(s["layout"]["restrictedZones"]),
            "walkthrough": bool(s.get("walkthrough", False)),
            "order_mode": bool(s.get("order_mode", False)),
            # fleet-sizing maps only; clients use it to show the placement step
            # (PC) or hide the card (mobile). None elsewhere keeps payload flat.
            "crane_choice": (dict(s["crane_choice"]) if s.get("crane_choice") else None),
        })
    # Sort by tier band, then difficulty, then walkthrough-first, then id.
    out.sort(key=lambda s: (
        TIER_ORDER.index(s["tier"]) if s["tier"] in TIER_ORDER else 99,
        s["difficulty"],
        0 if s.get("walkthrough") else 1,
        s["id"],
    ))
    return out


def get_scenario(scenario_id: str) -> Optional[Dict]:
    """Return a deep copy of a scenario by id, or None if not found.
    Deep copy so callers can mutate without affecting the registry.

    IDs that start with ``usr_`` are user-created scenarios stored in
    Postgres (see crane_db.storage.user_scenarios); we resolve those
    here so existing callers (human_play.create_session, etc.) keep
    working without branching on the id."""
    if scenario_id and scenario_id.startswith("usr_"):
        from crane_db import storage as _storage
        custom = _storage.get_user_scenario(scenario_id)
        return _storage.user_scenario_to_play_format(custom) if custom else None
    s = SCENARIOS.get(scenario_id)
    return copy.deepcopy(s) if s else None


def _diversify_standard(scenarios: Dict[str, Dict]) -> None:
    """Give STANDARD-tier lifts a spread of weights (and matching heights) so each
    lift's rated radius differs — the authored standard scenarios used a single
    uniform weight, which made every liftable-radius identical and hid the 2.5D
    effect. Tutorial (kept simple/uniform) and expert (already varied) are untouched.

    Weight cycle 8/12/16/20 t maps to distinct radii (~21/18/15/12 m at ground).
    Height is assigned INVERSELY to weight (light loads go high so height also bites,
    heavy loads stay low so they remain liftable after the crane repositions).
    Runs BEFORE _apply_tier_default_heights, which then leaves these z values alone.
    """
    weight_cycle = [8.0, 12.0, 16.0, 20.0]
    height_for = {8.0: 16.0, 12.0: 10.0, 16.0: 4.0, 20.0: 0.0}
    for scen in scenarios.values():
        if scen.get("tier") != "standard":
            continue
        for i, lift in enumerate(scen["layout"]["lifts"]):
            w = weight_cycle[i % len(weight_cycle)]
            lift["weight_t"] = w
            if "z" not in lift:
                lift["z"] = height_for[w]


def _apply_tier_default_heights(scenarios: Dict[str, Dict]) -> None:
    """Give every fixed-scenario lift a sample placement height (z) so the 2D
    rated-load chart actually engages across all tiers. Deterministic and editable:
    set `z` explicitly on a lift in its layout to override.

    Design intent (CLAUDE.md): tutorials stay at ground level so learners don't hit
    rated-load failures; standard gets modest heights; expert gets meaningful ones,
    but assigned INVERSELY to weight (heavy loads stay low) so every lift remains
    liftable once the crane repositions closer.
    """
    standard_cycle = [0.0, 4.0, 8.0]
    for scen in scenarios.values():
        tier = scen.get("tier")
        for i, lift in enumerate(scen["layout"]["lifts"]):
            if "z" in lift:
                continue  # respect explicit per-lift height
            if tier == "tutorial":
                z = 0.0
            elif tier == "standard":
                z = standard_cycle[i % len(standard_cycle)]
            else:  # expert: heavier loads placed lower to keep them feasible
                w = float(lift.get("weight_t", 10.0))
                z = 16.0 if w <= 10.0 else (10.0 if w <= 16.0 else 4.0)
            lift["z"] = z


_diversify_standard(SCENARIOS)
_apply_tier_default_heights(SCENARIOS)


# ─────────────────────────────────────────────────────────────────────────────
# Ordered ("순서") scenarios — dedicated maps the player works in a fixed,
# seeded-random erection order (no client toggle). Each clones a tuned base map
# so geometry/weights/heights are already balanced, then flips on order_mode;
# PlaySession reads that flag and gates candidates to the next-K in order. Built
# AFTER the height/weight passes so the clone inherits the finalized layout.
# ─────────────────────────────────────────────────────────────────────────────
# ``order_count`` = how many lifts carry the order; the rest are free. The
# engine seeds which specific lifts those are (see _apply_random_order).
_ORDERED_VARIANTS = [
    {
        "base": "D2_1", "id": "ORD_1", "tier": "tutorial", "difficulty": 2,
        "name": "순서 · 입문", "order_count": 3,
        "description": "번호가 붙은 일부 양중물만 순번대로, 나머지는 자유 — 크레인 2 · 양중 7(순서 3)",
    },
    {
        "base": "D3_1", "id": "ORD_2", "tier": "standard", "difficulty": 3,
        "name": "순서 · 표준", "order_count": 4,
        "description": "지정된 일부 양중물의 시공 순번을 지키며 진행 — 크레인 2 · 양중 10(순서 4)",
    },
    {
        "base": "D4_1", "id": "ORD_3", "tier": "expert", "difficulty": 4,
        "name": "순서 · 고급", "order_count": 4,
        "description": "일부 양중물 순서 제약 아래 3대 크레인 조율 — 크레인 3 · 양중 13(순서 4)",
    },
]


def _register_ordered_variants() -> None:
    for v in _ORDERED_VARIANTS:
        base = SCENARIOS.get(v["base"])
        if not base:  # base map missing — skip rather than break the pool
            continue
        scen = copy.deepcopy(base)
        scen.update({
            "id": v["id"],
            "tier": v["tier"],
            "name": v["name"],
            "description": v["description"],
            "difficulty": int(v["difficulty"]),
            "walkthrough": False,
            "order_mode": True,
            "order_count": int(v["order_count"]),
        })
        SCENARIOS[v["id"]] = scen


_register_ordered_variants()
