const W=100,H=100;
let pyResult=null,currentLevel=null,currentPolicyResult=null,replayTime=0,replayTimer=null;
const $=id=>document.getElementById(id);
function fmt(n,d=1){return Number.isFinite(+n)?(+n).toFixed(d):'-'}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function policyLabel(k){return k==='mappo'?'PyTorch MAPPO':k==='nearest'?'Nearest-lift-first':k==='radiusPriority'?'Same-radius-priority':k==='random'?'Random':k;}
function levelName(l){return l?.level?.name || l?.name || 'Level';}
function getLevels(){return pyResult?.levels || [];}
function normalizeSummary(x){return x||{};}
function importPyTorchResult(obj){pyResult=obj; const levels=getLevels(); const sel=$('levelSelect'); sel.innerHTML=levels.map((l,i)=>`<option value="${i}">${esc(levelName(l))}</option>`).join(''); $('loadStatus').textContent=`로드 완료: ${levels.length}개 level`; renderSelection();}
async function loadDefaultResult(){try{const r=await fetch($('resultPath').value); if(!r.ok) throw new Error(`HTTP ${r.status}`); importPyTorchResult(await r.json());}catch(e){$('loadStatus').textContent=`기본 결과 로드 실패: ${e.message}. 파일 선택으로 JSON을 불러오세요.`;}}
function loadFileResult(ev){const f=ev.target.files?.[0]; if(!f)return; const reader=new FileReader(); reader.onload=()=>{try{importPyTorchResult(JSON.parse(reader.result));}catch(e){$('loadStatus').textContent=`JSON 파싱 실패: ${e.message}`;}}; reader.readAsText(f);}
function selectedLevel(){return getLevels()[+$('levelSelect').value||0];}
function splitBlock(level,split){if(!level)return null; if(split==='representative')return level.representative||null; return level[split]||null;}
function summaryFromSplit(block,policy){if(!block)return null; if(block[policy])return normalizeSummary(block[policy]); return normalizeSummary(block);}
function representativeFor(level,policy){if(!level)return null; if(level.representative?.[policy])return level.representative[policy]; if(level.representative?.mappo)return level.representative.mappo; return null;}
function renderSelection(){const level=selectedLevel(); if(!level)return; currentLevel=level; const split=$('splitSelect').value, policy=$('policySelect').value, block=splitBlock(level,split); renderCompare(level,split); let shown=summaryFromSplit(block,policy); let rep=representativeFor(level,policy); currentPolicyResult=(split==='representative'&&shown?.events)?shown:(rep||shown||{}); renderMetrics(shown||currentPolicyResult||{}); renderLearningCharts(level); renderSchedule(currentPolicyResult||{}); setupReplay(currentPolicyResult||{}); drawReplayFrame(currentPolicyResult||{},replayTime);}
function renderMetrics(s){const total=s.total||currentLevel?.level?.num_lifts||0, done=s.done??Math.round((s.completeRate||0)/100*Math.max(1,total)); $('mComplete').textContent=s.completeRate?`${fmt(s.completeRate,1)}%`:`${done}/${total||'-'}`; $('mMakespan').textContent=fmt(s.makespan,1); $('mInterference').textContent=`S ${fmt(s.soft??s.softInter??0,1)} / EH ${fmt(s.hardExecuted??0,1)} / M ${fmt(s.hardMask??s.hardInter??0,1)}`; if($('mRestricted'))$('mRestricted').textContent=`M ${fmt(s.restrictedMask??0,1)} / E ${fmt(s.restrictedExecuted??0,1)} / D ${fmt(s.restrictedDetourDistance??0,1)}`; $('mEff').textContent=`${fmt(s.travel??s.travelTotal,1)} / ${fmt(s.setup??s.setupTotal,1)} / ${fmt(s.teardown??s.teardownTotal,1)} / ${fmt(s.move??s.moveTotal,1)}`;}
function renderCompare(level,split){const block=splitBlock(level,split==='representative'?'unseen':split)||{}; const keys=['mappo','nearest','radiusPriority','random'].filter(k=>block[k]); $('compareRows').innerHTML=keys.length?keys.map(k=>{const s=block[k];return `<tr><td>${policyLabel(k)}</td><td>${fmt(s.completeRate,1)}%</td><td>${fmt(s.makespan,2)}</td><td>${fmt(s.soft??s.softInter??0,2)}</td><td>${fmt(s.hardExecuted??0,2)}</td><td>${fmt(s.hardMask??s.hardInter??0,2)}</td><td>${fmt(s.restrictedMask??0,2)}</td><td>${fmt(s.travel??s.travelTotal,2)}</td><td>${fmt(s.setup??s.setupTotal,2)}</td><td>${fmt(s.teardown??s.teardownTotal,2)}</td><td>${fmt(s.move??s.moveTotal,2)}</td></tr>`}).join(''):'<tr><td colspan="11" class="note">비교 summary가 없습니다.</td></tr>';}
function renderSchedule(r){const cs=r.cranes||[]; if(cs.length&&cs.some(c=>c.schedule)){ $('scheduleText').textContent=cs.map(c=>`${c.id}\n  ${((c.schedule||[]).join('\n  '))||'(schedule text 없음)'}`).join('\n\n'); return;} const ev=r.events||[]; if(ev.length){const by={}; ev.slice().sort((a,b)=>a.start-b.start).forEach(e=>{(by[e.craneId] ||= []).push(`${e.liftId} ${fmt(e.start,1)}~${fmt(e.finish,1)}분 · teardown ${fmt(e.teardown,1)} travel ${fmt(e.travel,1)} setup ${fmt(e.setup,1)} lift ${fmt(e.duration,1)}${e.softConflict?' · Soft '+e.softConflict:''}${e.hardMask?' · HardMask '+e.hardMask:''}${e.restrictedMask?' · RestrictedMask '+e.restrictedMask:''}`);}); $('scheduleText').textContent=Object.keys(by).sort().map(k=>`${k}\n  ${by[k].join('\n  ')}`).join('\n\n'); return;} $('scheduleText').textContent='대표 schedule events가 없습니다. summary만 표시 중입니다.';}
function eventCraneIds(r){return [...new Set((r.events||[]).map(e=>e.craneId))].sort();}
function craneColor(i){return ['#38bdf8','#f87171','#34d399','#fbbf24','#a78bfa','#fb7185'][i%6];}
function sx(x,cv){return x/W*cv.width} function sy(y,cv){return y/H*cv.height}
function setupReplay(r){const max=Math.ceil(r.makespan||Math.max(1,...(r.events||[]).map(e=>e.finish||0))); $('replaySlider').max=max; replayTime=0; $('replaySlider').value=0; updateReplayInfo(r);}
function resetReplay(){replayTime=0; if(currentPolicyResult)drawReplayFrame(currentPolicyResult,0); $('replaySlider').value=0; updateReplayInfo(currentPolicyResult||{});}
function setReplayTime(t){replayTime=t; drawReplayFrame(currentPolicyResult||{},t); updateReplayInfo(currentPolicyResult||{});}
function toggleReplay(){if(replayTimer){clearInterval(replayTimer); replayTimer=null; $('playBtn').textContent='재생'; return;} $('playBtn').textContent='정지'; replayTimer=setInterval(()=>{const max=+$('replaySlider').max||1; replayTime=Math.min(max,replayTime+(+$('speed').value||1)); $('replaySlider').value=replayTime; drawReplayFrame(currentPolicyResult||{},replayTime); updateReplayInfo(currentPolicyResult||{}); if(replayTime>=max)toggleReplay();},180);}
function updateReplayInfo(r){const active=(r.events||[]).filter(e=>replayTime>=e.start&&replayTime<e.finish).map(e=>`${e.craneId}->${e.liftId}${(e.softConflict||e.interferenceLevel==='soft')?' ⚠S':''}`); $('replayInfo').textContent=`현재 ${Math.round(replayTime)} / ${Math.ceil(r.makespan||0)}분 · 진행 중: ${active.join(', ')||'없음'}`;}
function eventPos(e,t){const path=(e.movePath&&e.movePath.length?e.movePath:[{x:e.fromX??e.radiusCenterX??0,y:e.fromY??e.radiusCenterY??0},{x:e.toX??e.radiusCenterX??0,y:e.toY??e.radiusCenterY??0}]); if(t<e.start)return {x:path[0].x,y:path[0].y,active:false}; if(t>=e.finish)return {x:path[path.length-1].x,y:path[path.length-1].y,active:false}; const travel=e.travel||0, moveStart=e.travelStart??e.start, moveEnd=e.travelFinish??(moveStart+travel); if(travel>0&&t>=moveStart&&t<moveEnd){const total=path.slice(1).reduce((s,p,i)=>s+Math.hypot(p.x-path[i].x,p.y-path[i].y),0)||1; let remain=((t-moveStart)/Math.max(.001,travel))*total; for(let i=1;i<path.length;i++){const a=path[i-1],b=path[i],seg=Math.hypot(b.x-a.x,b.y-a.y); if(remain<=seg){const u=remain/Math.max(.001,seg); return {x:a.x+(b.x-a.x)*u,y:a.y+(b.y-a.y)*u,active:true};} remain-=seg;} return {x:path[path.length-1].x,y:path[path.length-1].y,active:true};} return t<moveEnd?{x:path[0].x,y:path[0].y,active:true}:{x:e.toX??e.radiusCenterX??0,y:e.toY??e.radiusCenterY??0,active:true};}
function drawCircle(ctx,cv,x,y,r,color,dashed=false,alpha=.65){ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=2;if(dashed)ctx.setLineDash([7,5]);ctx.beginPath();ctx.ellipse(sx(x,cv),sy(y,cv),r/W*cv.width,r/H*cv.height,0,0,Math.PI*2);ctx.stroke();ctx.restore();}
function drawRestrictedZones(ctx,cv,zones){(zones||[]).forEach(z=>{const x=Math.min(+z.x1,+z.x2), y=Math.min(+z.y1,+z.y2), w=Math.abs(+z.x2-+z.x1), h=Math.abs(+z.y2-+z.y1); ctx.save();ctx.fillStyle='rgba(239,68,68,.24)';ctx.strokeStyle='#ef4444';ctx.lineWidth=2;ctx.fillRect(sx(x,cv),sy(y,cv),w/W*cv.width,h/H*cv.height);ctx.strokeRect(sx(x,cv),sy(y,cv),w/W*cv.width,h/H*cv.height);ctx.strokeStyle='rgba(248,113,113,.55)';for(let i=-h;i<w+h;i+=6){ctx.beginPath();ctx.moveTo(sx(x+i,cv),sy(y,cv));ctx.lineTo(sx(x+i+h,cv),sy(y+h,cv));ctx.stroke();}ctx.fillStyle='#fecaca';ctx.fillText(z.id||'RZ',sx(x,cv)+6,sy(y,cv)+16);ctx.restore();});}
function drawReplayFrame(r,t){const cv=$('replayCanvas'),ctx=cv.getContext('2d');ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle='#020617';ctx.fillRect(0,0,cv.width,cv.height);ctx.strokeStyle='#1e293b';ctx.lineWidth=1;for(let g=0;g<=100;g+=20){ctx.beginPath();ctx.moveTo(sx(g,cv),0);ctx.lineTo(sx(g,cv),cv.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,sy(g,cv));ctx.lineTo(cv.width,sy(g,cv));ctx.stroke();} drawRestrictedZones(ctx,cv,r.restrictedZones||r.layout?.restrictedZones||[]);
 const events=r.events||[], craneIds=eventCraneIds(r); const active=new Set(); events.forEach(e=>{const ci=Math.max(0,craneIds.indexOf(e.craneId)), color=craneColor(ci); const path=e.movePath||[]; if(path.length>1 && t>=e.start){ctx.save();ctx.strokeStyle=color;ctx.globalAlpha=.55;ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(sx(path[0].x,cv),sy(path[0].y,cv));for(let pi=1;pi<path.length;pi++)ctx.lineTo(sx(path[pi].x,cv),sy(path[pi].y,cv));ctx.stroke();ctx.restore();} const done=t>=e.finish, hoisting=t>=(e.liftStart??e.start)&&t<e.finish; if(done||hoisting){ctx.fillStyle=color;ctx.globalAlpha=done?.55:1;ctx.beginPath();ctx.arc(sx(e.liftX??0,cv),sy(e.liftY??0,cv),hoisting?7:5,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillText(e.liftId||'',sx(e.liftX??0,cv)+7,sy(e.liftY??0,cv)-7);} if(hoisting){active.add(e.craneId); const cx=e.radiusCenterX??e.toX??0, cy=e.radiusCenterY??e.toY??0, actual=e.actualLiftRadius??0, cr=e.craneRadius??e.dangerRadius??currentLevel?.config?.crane_radius??18; drawCircle(ctx,cv,cx,cy,cr,color,true,.75); drawCircle(ctx,cv,cx,cy,actual,'#e5e7eb',false,.85); ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(sx(cx,cv),sy(cy,cv));ctx.lineTo(sx(e.liftX??cx,cv),sy(e.liftY??cy,cv));ctx.stroke();}});
 craneIds.forEach((id,i)=>{const evs=events.filter(e=>e.craneId===id).sort((a,b)=>a.start-b.start); let pos=evs.length?eventPos(evs[0],t):{x:8+i*10,y:8}; for(const e of evs){if(t>=e.start)pos=eventPos(e,t); if(t<e.start)break;} const color=craneColor(i); ctx.fillStyle=color;ctx.beginPath();ctx.arc(sx(pos.x,cv),sy(pos.y,cv),9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e5e7eb';ctx.fillText(id,sx(pos.x,cv)+10,sy(pos.y,cv)+4);});
 ctx.fillStyle='#cbd5e1';ctx.fillText('Soft=craneRadius overlap / Hard=actualLiftRadius overlap',12,cv.height-14);}



function showTab(name){document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===name)); document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active')); const btn=$('tabBtn-'+name); if(btn)btn.classList.add('active'); if(name==='plan')drawPlanEditor();}
let planCranes=[], planLifts=[], planRestrictedZones=[], planDrag=null;
function clamp(v){return Math.max(0,Math.min(100,v));}
function initPlanLayout(){planCranes=[{id:'C1',x:15,y:20},{id:'C2',x:75,y:25},{id:'C3',x:45,y:80}]; planLifts=Array.from({length:12},(_,i)=>({id:'L'+(i+1),x:15+(i%4)*20,y:42+Math.floor(i/4)*16})); planRestrictedZones=[{id:'RZ1',type:'rect',x1:40,y1:40,x2:60,y2:60}]; syncPlanText(); drawPlanEditor(); $('planStatus').textContent='기본 현장 배치와 제한구역을 생성했습니다.';}
function syncPlanText(){if(!$('planLayoutText'))return; $('planLayoutText').value=[...planCranes.map(c=>`crane,${c.id},${fmt(c.x,2)},${fmt(c.y,2)}`),...planLifts.map(l=>`lift,${l.id},${fmt(l.x,2)},${fmt(l.y,2)}`),...planRestrictedZones.map(z=>`restricted,${z.id},${fmt(z.x1,2)},${fmt(z.y1,2)},${fmt(z.x2,2)},${fmt(z.y2,2)}`)].join('\n');}
function applyPlanText(){const lines=$('planLayoutText').value.split(/\n+/), cs=[], ls=[], zs=[]; for(const line of lines){const p=line.split(',').map(x=>x.trim()); if(p.length<4)continue; const kind=p[0].toLowerCase(); if(kind==='crane')cs.push({id:p[1],x:clamp(+p[2]),y:clamp(+p[3])}); if(kind==='lift')ls.push({id:p[1],x:clamp(+p[2]),y:clamp(+p[3])}); if(['restricted','zone','rz'].includes(kind)&&p.length>=6)zs.push({id:p[1],type:'rect',x1:clamp(+p[2]),y1:clamp(+p[3]),x2:clamp(+p[4]),y2:clamp(+p[5])});} if(cs.length)planCranes=cs; if(ls.length)planLifts=ls; planRestrictedZones=zs; syncPlanText(); drawPlanEditor();}
function addPlanCrane(){planCranes.push({id:'C'+(planCranes.length+1),x:10+planCranes.length*12,y:10}); syncPlanText(); drawPlanEditor();}
function addPlanLift(){planLifts.push({id:'L'+(planLifts.length+1),x:50,y:50}); syncPlanText(); drawPlanEditor();}
function addPlanRestrictedZone(){planRestrictedZones.push({id:'RZ'+(planRestrictedZones.length+1),type:'rect',x1:40,y1:40,x2:60,y2:60}); syncPlanText(); drawPlanEditor();}
function planCanvasXY(ev){const cv=$('planCanvas'),r=cv.getBoundingClientRect(); return {x:clamp((ev.clientX-r.left)/r.width*100), y:clamp((ev.clientY-r.top)/r.height*100)};}
function nearestPlanItem(pt){const target=$('planEditTarget')?.value||'all'; let best=null; function test(type,item,idx,rad){const d=Math.hypot(item.x-pt.x,item.y-pt.y); if(d<rad && (!best||d<best.d))best={type,item,idx,d};} if(target!=='lift')planCranes.forEach((c,i)=>test('crane',c,i,4)); if(target!=='crane')planLifts.forEach((l,i)=>test('lift',l,i,3)); return best;}
function drawPlanEditor(){const cv=$('planCanvas'); if(!cv)return; const ctx=cv.getContext('2d'); ctx.clearRect(0,0,cv.width,cv.height); ctx.fillStyle='#020617';ctx.fillRect(0,0,cv.width,cv.height); ctx.strokeStyle='#1e293b'; for(let g=0;g<=100;g+=20){ctx.beginPath();ctx.moveTo(sx(g,cv),0);ctx.lineTo(sx(g,cv),cv.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,sy(g,cv));ctx.lineTo(cv.width,sy(g,cv));ctx.stroke();} drawRestrictedZones(ctx,cv,planRestrictedZones); const cr=+$('planCraneRadius')?.value||18; planLifts.forEach(l=>{ctx.fillStyle='#f59e0b';ctx.beginPath();ctx.arc(sx(l.x,cv),sy(l.y,cv),6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e5e7eb';ctx.fillText(l.id,sx(l.x,cv)+7,sy(l.y,cv)-7);}); planCranes.forEach((c,i)=>{drawCircle(ctx,cv,c.x,c.y,cr,craneColor(i),true,.6); ctx.fillStyle=craneColor(i);ctx.fillRect(sx(c.x,cv)-8,sy(c.y,cv)-8,16,16);ctx.fillStyle='#e5e7eb';ctx.fillText(c.id,sx(c.x,cv)+10,sy(c.y,cv)+4);});}
function installPlanCanvasHandlers(){const cv=$('planCanvas'); if(!cv||cv._installed)return; cv._installed=true; cv.addEventListener('mousedown',ev=>{const pt=planCanvasXY(ev); planDrag=nearestPlanItem(pt);}); window.addEventListener('mousemove',ev=>{if(!planDrag)return; const pt=planCanvasXY(ev); planDrag.item.x=pt.x; planDrag.item.y=pt.y; syncPlanText(); drawPlanEditor();}); window.addEventListener('mouseup',()=>{planDrag=null;});}
async function runPlanningAgent(){applyPlanText(); const payload={modelPath:$('planModelPath').value,policy:$('planPolicy').value,candidate_k:num('planCandidateK'),max_steps:num('planMaxSteps'),fixed_duration:num('planFixedDuration'),setup_time:num('planSetupTime'),teardown_time:num('planTeardownTime'),crane_radius:num('planCraneRadius'),cranes:planCranes,lifts:planLifts,restrictedZones:planRestrictedZones,r_single:num('rwSingle'),r_all:num('rwAll'),r_same:num('rwSame'),p_idle:num('rwIdle'),p_inter_soft:num('rwSoft'),p_time:num('rwTime'),p_move:num('rwMove')}; $('planStatus').textContent='현재 배치로 양중계획 생성 중...'; try{const r=await fetch('/api/plan/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const data=await r.json(); if(!data.ok)throw new Error(data.message||'planning failed'); currentPolicyResult=data.result; currentLevel={level:{num_lifts:planLifts.length},config:{crane_radius:payload.crane_radius}}; renderMetrics(currentPolicyResult); renderCompare({unseen:{[payload.policy]:currentPolicyResult}},'unseen'); renderSchedule(currentPolicyResult); setupReplay(currentPolicyResult); drawReplayFrame(currentPolicyResult,0); $('planStatus').textContent=`계획 생성 완료: makespan ${fmt(currentPolicyResult.makespan,1)}, 완료 ${currentPolicyResult.done}/${currentPolicyResult.total}, HardExecuted ${currentPolicyResult.hardExecuted}, RestrictedExecuted ${currentPolicyResult.restrictedExecuted??0}`; showTab('results');}catch(e){$('planStatus').textContent=`계획 생성 실패: ${e.message}. 서버로 열었는지 확인하세요.`;}}

function num(id){const v=+$((id)).value; return Number.isFinite(v)?v:null;}
function trainingPayload(){return {
  episodes:num('trEpisodes'), num_cranes:num('trNumCranes'), num_lifts:num('trNumLifts'), candidate_k:num('trCandidateK'), base_seed:num('trBaseSeed'), seed_runs:num('trSeedRuns'), fixed_duration:num('trFixedDuration'), setup_time:num('trSetupTime'), teardown_time:num('trTeardownTime'), crane_radius:num('trCraneRadius'),
  seen_seed_start:num('trSeenStart'), seen_seed_count:num('trSeenCount'), validation_seed_start:num('trValStart'), validation_seed_count:num('trValCount'), unseen_seed_start:num('trUnseenStart'), unseen_seed_count:num('trUnseenCount'),
  r_single:num('rwSingle'), r_all:num('rwAll'), r_same:num('rwSame'), p_idle:num('rwIdle'), p_inter_soft:num('rwSoft'), p_time:num('rwTime'), p_move:num('rwMove')
};}
function setVal(id,v){if($(id)&&v!==undefined&&v!==null)$(id).value=v;}
let _syncingTeardownTime=false;
function syncTeardownTime(sourceId){if(_syncingTeardownTime)return; const src=$(sourceId), dst=$(sourceId==='trTeardownTime'?'planTeardownTime':'trTeardownTime'); if(!src||!dst)return; _syncingTeardownTime=true; dst.value=src.value; _syncingTeardownTime=false;}
function installTeardownTimeSync(){['trTeardownTime','planTeardownTime'].forEach(id=>{const el=$(id); if(!el||el._teardownSyncInstalled)return; el._teardownSyncInstalled=true; el.addEventListener('input',()=>syncTeardownTime(id)); el.addEventListener('change',()=>syncTeardownTime(id));}); syncTeardownTime('trTeardownTime');}
async function loadTrainingDefaults(){try{const r=await fetch('/api/config'); if(!r.ok)throw new Error(`HTTP ${r.status}`); const c=await r.json(); setVal('trEpisodes',c.train_episodes); setVal('trNumCranes',c.num_cranes); setVal('trNumLifts',c.num_lifts); setVal('trCandidateK',c.candidate_k); setVal('trBaseSeed',c.base_seed); setVal('trSeedRuns',c.seed_runs); setVal('trFixedDuration',c.fixed_duration); setVal('trSetupTime',c.setup_time); setVal('trTeardownTime',c.teardown_time??5); syncTeardownTime('trTeardownTime'); setVal('trCraneRadius',c.crane_radius); setVal('trSeenStart',c.seen_seed_start); setVal('trSeenCount',c.seen_seed_count); setVal('trValStart',c.validation_seed_start); setVal('trValCount',c.validation_seed_count); setVal('trUnseenStart',c.unseen_seed_start); setVal('trUnseenCount',c.unseen_seed_count); const rw=c.reward||{}; setVal('rwSingle',rw.r_single); setVal('rwAll',rw.r_all); setVal('rwSame',rw.r_same); setVal('rwIdle',rw.p_idle); setVal('rwSoft',rw.p_inter_soft); setVal('rwTime',rw.p_time); setVal('rwMove',rw.p_move); $('trainStatus').textContent='현재 config를 대시보드 입력값으로 불러왔습니다.'; renderTrainingCommand();}catch(e){$('trainStatus').textContent=`config 로드 실패: ${e.message}. 서버로 열었는지 확인하세요.`;}}
function renderTrainingCommand(){const p=trainingPayload(); const outdir=`python_mappo/dashboard_runs/run_YYYYMMDD_HHMMSS`; const cmd=`python3 -m python_mappo.train --config ${outdir}/config.yaml --episodes ${p.episodes} --outdir ${outdir} --validation-start ${p.validation_seed_start} --validation-count ${p.validation_seed_count} --unseen-start ${p.unseen_seed_start} --unseen-count ${p.unseen_seed_count}`; $('trainCommand').textContent=`보상함수: R = ${p.r_single}*complete + ${p.r_all}*allDone + ${p.r_same}*sameRadius + (${p.p_idle})*idle + (${p.p_inter_soft})*soft + (${p.p_time})*taskTime + (${p.p_move})*moveDistance\n\n${cmd}`;}
let currentJobId=null, trainPollTimer=null;
async function launchPyTorchRun(){renderTrainingCommand(); try{const r=await fetch('/api/train/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(trainingPayload())}); const data=await r.json(); if(!data.ok)throw new Error(data.message||'start failed'); currentJobId=data.job.jobId; $('trainStatus').textContent=`학습 시작: ${currentJobId}`; $('trainLog').textContent=data.job.command||''; if(trainPollTimer)clearInterval(trainPollTimer); trainPollTimer=setInterval(pollTrainingStatus,2500); await pollTrainingStatus();}catch(e){$('trainStatus').textContent=`학습 시작 실패: ${e.message}. npm run serve/python3 app.py로 연 대시보드인지 확인하세요.`;}}
async function pollTrainingStatus(){try{const url=currentJobId?`/api/train/status?jobId=${encodeURIComponent(currentJobId)}`:'/api/train/status'; const r=await fetch(url); const data=await r.json(); if(!data.ok)throw new Error(data.message||'status failed'); const j=data.job; currentJobId=j.jobId; $('trainStatus').textContent=`${j.jobId} · ${j.running?'실행 중':'종료'} · exit=${j.exitCode??'-'} · 결과=${j.resultPath}`; $('trainLog').textContent=(j.logTail||[]).join('\n') || j.command || '';
    if(!j.running){if(trainPollTimer){clearInterval(trainPollTimer);trainPollTimer=null;} if(j.resultExists){$('resultPath').value=j.resultPath; $('trainStatus').textContent += ' · 결과 경로를 불러오기 입력칸에 반영했습니다.';}}
  }catch(e){$('trainStatus').textContent=`상태 확인 실패: ${e.message}`;}}

function curveForLevel(level){
  const all=pyResult?.learningCurve||level?.learningCurve||[];
  const name=levelName(level);
  if(!all.length)return [];
  const filtered=all.filter(e=>!e.level||e.level===name||e.level===level?.level?.name);
  return filtered.length?filtered:all;
}
function mean(arr,key){const vals=arr.map(x=>+x[key]).filter(Number.isFinite); return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:NaN;}
function smoothSeries(data,key,window=15){return data.map((d,i)=>{const a=data.slice(Math.max(0,i-window+1),i+1); return {ep:d.ep??i+1, value:mean(a,key), raw:+d[key]};}).filter(d=>Number.isFinite(d.value));}
function drawLineChart(canvasId,series,opts={}){const cv=$(canvasId),ctx=cv.getContext('2d'),pad=34;ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle='#020617';ctx.fillRect(0,0,cv.width,cv.height);ctx.strokeStyle='#1e293b';ctx.lineWidth=1;for(let i=0;i<=4;i++){const y=pad+(cv.height-pad*1.6-pad)*i/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(cv.width-pad/2,y);ctx.stroke();} const flat=series.flatMap(s=>s.points.map(p=>p.value)).filter(Number.isFinite); if(!flat.length){ctx.fillStyle='#94a3b8';ctx.fillText('learningCurve 데이터가 없습니다.',pad,cv.height/2);return;} const minY=opts.minY??Math.min(...flat), maxY=opts.maxY??Math.max(...flat), span=Math.max(1e-6,maxY-minY); const maxX=Math.max(1,...series.flatMap(s=>s.points.map(p=>p.ep||1))); const x=v=>pad+(v-1)/Math.max(1,maxX-1)*(cv.width-pad*1.5); const y=v=>cv.height-pad-(v-minY)/span*(cv.height-pad*1.8); ctx.fillStyle='#94a3b8';ctx.fillText(fmt(minY,1),4,cv.height-pad);ctx.fillText(fmt(maxY,1),4,pad);ctx.fillText(`ep 1-${maxX}`,cv.width-92,cv.height-8); series.forEach((s,idx)=>{ctx.strokeStyle=s.color||craneColor(idx);ctx.lineWidth=2;ctx.beginPath();s.points.forEach((p,i)=>{if(i===0)ctx.moveTo(x(p.ep),y(p.value));else ctx.lineTo(x(p.ep),y(p.value));});ctx.stroke();ctx.fillStyle=s.color||craneColor(idx);ctx.fillText(s.label,pad+idx*130,16);});}
function renderLearningCharts(level){const curve=curveForLevel(level); const first=curve.slice(0,10), last=curve.slice(-20); $('gEpisodes').textContent=curve.length?`${curve.length}`:'-'; $('gFirstReward').textContent=fmt(mean(first,'reward'),1); $('gLastReward').textContent=fmt(mean(last,'reward'),1); $('gLastMakespan').textContent=fmt(mean(last,'makespan'),1); drawLineChart('rewardChart',[{label:'reward(15ep avg)',points:smoothSeries(curve,'reward'),color:'#22c55e'}]); drawLineChart('makespanChart',[{label:'makespan(15ep avg)',points:smoothSeries(curve,'makespan'),color:'#38bdf8'}]); drawLineChart('interChart',[{label:'soft',points:smoothSeries(curve,'soft'),color:'#f59e0b'},{label:'hardMask',points:smoothSeries(curve,'hardMask'),color:'#ef4444'},{label:'hardExecuted',points:smoothSeries(curve,'hardExecuted'),color:'#a78bfa'}],{minY:0}); drawLineChart('effChart',[{label:'travel',points:smoothSeries(curve,'travel'),color:'#38bdf8'},{label:'setup',points:smoothSeries(curve,'setup'),color:'#fbbf24'},{label:'move',points:smoothSeries(curve,'move'),color:'#34d399'}],{minY:0});}

function downloadCurrentEventsCsv(){const ev=currentPolicyResult?.events||[]; if(!ev.length)return; const rows=[['craneId','liftId','start','finish','radiusCenterX','radiusCenterY','liftX','liftY','actualLiftRadius','craneRadius','softInterference','hardMask']]; ev.forEach(e=>rows.push([e.craneId,e.liftId,e.start,e.finish,e.radiusCenterX,e.radiusCenterY,e.liftX,e.liftY,e.actualLiftRadius,e.craneRadius??e.dangerRadius??'',e.softConflict||0,e.hardMask||0])); const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'); const blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='pytorch_mappo_events.csv';a.click();URL.revokeObjectURL(url);}
window.addEventListener('load',()=>{drawReplayFrame({},0); installPlanCanvasHandlers(); installTeardownTimeSync(); initPlanLayout();});
